apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: techtrends-staging
  name: techtrends-staging
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: techtrends-staging
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: techtrends-staging
    spec:
      containers:
      - image: nickwooduk/techtrends:latest
        imagePullPolicy: IfNotPresent
        name: techtrends
        resources:
          requests:
            cpu: 250m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 128Mi
