namespace:
  name: sandbox
 
service:
  port: 4111
  targetPort: 3111
  type: ClusterIP
  protocol: TCP

image:
  repository: nickwooduk/techtrends
  tag: main
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  requests:
    cpu: 250m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 128Mi

